---
- name: Retrieve secret from Vault
  hosts: localhost
  tasks:
    - name: Get secret from Vault
      hashivault_secret:
        url: "http://localhost:8200"
        token: "{{ vault_token }}"
        secret: "secret/myapp/config"
      register: secret_data

    - name: Use the retrieved secret in the script
      debug:
        msg: "Retrieved secret: {{ secret_data.data.value }}"
