---
- name: Run Vault Python script
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Make script executable (optional)
      ansible.builtin.file:
        path: vault-secrets-playbook.py
        mode: '0755'

    - name: Execute the vault-secrets Python script
      ansible.builtin.command: python3 vault-secrets-playbook.py
